# Generated by Django 4.2.3 on 2023-07-20 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company_url', models.URLField()),
                ('genre_id', models.IntegerField()),
                ('release_date', models.DateTimeField()),
                ('artwork_large_url', models.URLField()),
                ('seller_name', models.CharField(max_length=50)),
                ('five_star_ratings', models.IntegerField()),
                ('four_star_ratings', models.IntegerField()),
                ('three_star_ratings', models.IntegerField()),
                ('two_star_ratings', models.IntegerField()),
                ('one_star_ratings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sdk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30)),
                ('url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AppSdk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed', models.BooleanField(blank=True, default=False, null=True)),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.app')),
                ('sdk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.sdk')),
            ],
        ),
    ]
